"use client"

import { useEffect, useState } from "react"
import { useSession } from "next-auth/react"
import { Leaf, Bell, Search, Plus, Download, ArrowUp, Zap, Truck, ShoppingCart, DollarSign, Database, AlertCircle, Loader2 } from "lucide-react"
import { SubTabs } from "@/components/sub-tabs"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { apiFetch } from "@/lib/api"
import type { CarbonTransaction, PaginatedResponse } from "@/lib/types"

const tabs = [
  { name: "Emission Factors", href: "/environmental/emission-factors" },
  { name: "Product ESG Profiles", href: "/environmental/products" },
  { name: "Carbon Transactions", href: "/environmental/transactions" },
  { name: "Environmental Goals", href: "/environmental" },
]

function getSourceIcon(type: string) {
  switch (type) {
    case "PURCHASE": return <ShoppingCart className="h-4 w-4" />
    case "MANUFACTURING": return <Zap className="h-4 w-4" />
    case "FLEET": return <Truck className="h-4 w-4" />
    case "EXPENSE": return <DollarSign className="h-4 w-4" />
    default: return <Database className="h-4 w-4" />
  }
}

function getSourceColor(type: string) {
  switch (type) {
    case "PURCHASE": return "bg-[#E2F1E3] text-[#0D631B]"
    case "MANUFACTURING": return "bg-[#F2ECF7] text-[#7A2FAA]"
    case "FLEET": return "bg-[#E1F0FF] text-[#005DB7]"
    case "EXPENSE": return "bg-[#FFE0B2] text-[#E65100]"
    default: return "bg-[#E2E8F0] text-[#40493d]"
  }
}

export default function CarbonTransactionsPage() {
  const { data: session } = useSession()
  const [transactions, setTransactions] = useState<CarbonTransaction[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [search, setSearch] = useState("")
  const pageSize = 15

  useEffect(() => {
    if (!session?.accessToken) return

    const fetchTransactions = async () => {
      setLoading(true)
      setError(null)
      try {
        let url = `/environmental/carbon-transactions?page=${page}&page_size=${pageSize}`
        if (search) {
          url += `&sourceType=${encodeURIComponent(search.toUpperCase())}`
        }
        const data = await apiFetch<PaginatedResponse<CarbonTransaction>>(
          url,
          {},
          session.accessToken
        )
        setTransactions(data.items)
        setTotal(data.total)
      } catch (err: any) {
        console.error("[CarbonTransactions] Fetch error:", err)
        setError(err.detail || "Failed to load carbon transactions")
      } finally {
        setLoading(false)
      }
    }

    fetchTransactions()
  }, [session?.accessToken, page, search])

  const totalPages = Math.max(1, Math.ceil(total / pageSize))

  // Metrics
  const totalEmissions = transactions.reduce((acc, tx) => acc + tx.co2Calculated, 0)
  const autoGeneratedCount = transactions.filter(tx => tx.autoGenerated).length
  const autoGeneratedPct = transactions.length ? (autoGeneratedCount / transactions.length) * 100 : 0
  const anomaliesCount = transactions.filter(tx => tx.anomalyFlag).length

  return (
    <div className="flex w-full flex-col bg-[#F7F8FA] min-h-screen">
      {/* Top Header */}
      <header className="flex h-[72px] items-center justify-between border-b border-[#E2E8F0] bg-white px-8">
        <div className="flex items-center gap-3">
          <Leaf className="h-6 w-6 text-[#0D631B]" />
          <h1 className="text-[24px] font-semibold text-[#191C1E]">Environmental Module</h1>
        </div>
        <div className="flex items-center gap-4">
          <div className="relative w-[300px]">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#707A6C]" />
            <Input
              placeholder="Search source type (e.g. FLEET)..."
              value={search}
              onChange={(e) => { setSearch(e.target.value); setPage(1) }}
              className="h-[40px] w-full rounded-full border border-[#E2E8F0] bg-[#F7F8FA]/50 pl-9 focus-visible:ring-[#0D631B]"
            />
          </div>
          <button className="flex h-10 w-10 items-center justify-center rounded-full text-[#40493d] hover:bg-[#E2E8F0] transition-colors">
            <Bell className="h-5 w-5" />
          </button>
        </div>
      </header>

      {/* Sub Tabs */}
      <SubTabs tabs={tabs} activeTabName="Carbon Transactions" activeColor="#0D631B" />

      {/* Main Content */}
      <main className="flex-1 p-8">
        <div className="mx-auto max-w-7xl space-y-6">
          
          {/* Breadcrumbs & Title Actions */}
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.05em] text-[#707A6C] mb-2">
                <span className="text-[#707A6C]">ENVIRONMENTAL</span>
                <span className="text-[#E2E8F0]">/</span>
                <span className="text-[#191C1E]">CARBON TRANSACTIONS</span>
              </div>
              <h2 className="text-[32px] font-bold text-[#191C1E] tracking-tight leading-none">Activity Emissions Ledger</h2>
            </div>

            {/* Actions */}
            <div className="flex items-center gap-3">
              <Button variant="outline" className="h-[40px] gap-2 border-[#E2E8F0] text-[#191C1E] font-semibold rounded-[8px] bg-white hover:bg-[#F7F8FA] transition-colors px-4">
                <Download className="h-4 w-4" />
                Export CSV
              </Button>
              <Button className="h-[40px] gap-2 bg-[#0D631B] hover:bg-[#1b6d24] text-white font-semibold rounded-[8px] px-4 transition-colors">
                <Plus className="h-4 w-4" />
                Log Transaction
              </Button>
            </div>
          </div>

          {/* Metrics Row */}
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
            
            {/* Card 1: Total Records */}
            <div className="rounded-[16px] border-l-4 border-l-[#0D631B] border border-[#E2E8F0] bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.02)] flex flex-col justify-between h-[135px]">
              <div className="flex items-center justify-between">
                <span className="text-[12px] font-bold uppercase tracking-[0.05em] text-[#707A6C]">Total Records</span>
                <span className="inline-flex items-center gap-0.5 rounded-full bg-[#E2F1E3] px-2.5 py-0.5 text-[11px] font-bold text-[#0D631B]">
                  Live
                </span>
              </div>
              <div className="flex items-baseline gap-1 mt-auto">
                <span className="text-[32px] font-bold text-[#191C1E] tracking-tight">
                  {loading ? "—" : total.toLocaleString()}
                </span>
                <span className="text-[14px] text-[#707A6C] font-semibold mb-1">tx</span>
              </div>
            </div>

            {/* Card 2: Total Emissions */}
            <div className="rounded-[16px] border-l-4 border-l-[#005DB7] border border-[#E2E8F0] bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.02)] flex flex-col justify-between h-[135px]">
              <div className="flex items-center justify-between">
                <span className="text-[12px] font-bold uppercase tracking-[0.05em] text-[#707A6C]">Total Emissions</span>
              </div>
              <div className="flex flex-col mt-auto">
                <div className="flex items-baseline gap-1">
                  <span className="text-[32px] font-bold text-[#191C1E] tracking-tight">
                    {loading ? "—" : totalEmissions.toLocaleString(undefined, { maximumFractionDigits: 1 })}
                  </span>
                  <span className="text-[14px] text-[#707A6C] font-semibold">kg CO2e</span>
                </div>
                <span className="text-[11px] text-[#707A6C] font-semibold mt-1">Current page</span>
              </div>
            </div>

            {/* Card 3: Auto-Generated */}
            <div className="rounded-[16px] border-l-4 border-l-[#7A2FAA] border border-[#E2E8F0] bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.02)] flex flex-col justify-between h-[135px]">
              <span className="text-[12px] font-bold uppercase tracking-[0.05em] text-[#707A6C]">Auto-Generated</span>
              <div className="flex flex-col mt-auto">
                <div className="flex items-baseline gap-1">
                  <span className="text-[32px] font-bold text-[#191C1E] tracking-tight">
                    {loading ? "—" : `${autoGeneratedPct.toFixed(1)}%`}
                  </span>
                </div>
                <span className="text-[11px] text-[#0D631B] font-bold mt-1 flex items-center gap-0.5">
                  <ArrowUp className="h-3 w-3 stroke-[2.5]" /> Efficiency tracking
                </span>
              </div>
            </div>

            {/* Card 4: Anomalies */}
            <div className="rounded-[16px] border-l-4 border-l-[#BA1A1A] border border-[#E2E8F0] bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.02)] flex flex-col justify-between h-[135px]">
              <span className="text-[12px] font-bold uppercase tracking-[0.05em] text-[#707A6C]">Data Anomalies</span>
              <div className="flex flex-col mt-auto">
                <div className="flex items-baseline gap-1">
                  <span className="text-[32px] font-bold text-[#191C1E] tracking-tight">
                    {loading ? "—" : anomaliesCount}
                  </span>
                  <span className="text-[14px] text-[#707A6C] font-semibold">flags</span>
                </div>
                <span className="text-[11px] text-[#BA1A1A] font-semibold mt-1">
                  Require manual review
                </span>
              </div>
            </div>

          </div>

          {/* Transaction History Section */}
          <div className="overflow-hidden rounded-[16px] border border-[#E2E8F0] bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.02)] space-y-6">
            
            {/* Header controls */}
            <div className="flex items-center justify-between border-b border-[#E2E8F0] pb-4">
              <div className="flex items-center gap-3">
                <h3 className="text-[18px] font-bold text-[#191C1E]">Transactions Ledger</h3>
                <span className="inline-flex items-center gap-1 rounded-full bg-[#E2F1E3] px-2.5 py-0.5 text-[11px] font-bold text-[#0D631B]">
                  <span className="h-1.5 w-1.5 rounded-full bg-[#0D631B] animate-pulse"></span>
                  Live Sync
                </span>
              </div>
              <span className="text-[12px] font-semibold text-[#707A6C]">
                {loading ? "Loading..." : `Showing ${transactions.length} of ${total.toLocaleString()}`}
              </span>
            </div>

            {/* Table */}
            {loading ? (
              <div className="flex items-center justify-center py-16">
                <Loader2 className="h-6 w-6 animate-spin text-[#0D631B]" />
                <span className="ml-3 text-[14px] text-[#707A6C]">Loading transactions...</span>
              </div>
            ) : error ? (
              <div className="flex flex-col items-center justify-center py-16 text-center">
                <p className="text-[14px] font-medium text-[#BA1A1A]">{error}</p>
                <Button
                  variant="outline"
                  className="mt-4 text-[13px]"
                  onClick={() => setPage(page)}
                >
                  Retry
                </Button>
              </div>
            ) : transactions.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 text-center">
                <Database className="h-10 w-10 text-[#E2E8F0] mb-3" />
                <p className="text-[14px] font-medium text-[#707A6C]">No carbon transactions found</p>
                <p className="text-[12px] text-[#707A6C] mt-1">Transactions will appear here when generated</p>
              </div>
            ) : (
              <div className="w-full">
                <Table>
                  <TableHeader>
                    <TableRow className="border-b-[#E2E8F0] hover:bg-transparent">
                      <TableHead className="h-10 text-[11px] font-bold uppercase tracking-[0.05em] text-[#40493d]">Date</TableHead>
                      <TableHead className="h-10 text-[11px] font-bold uppercase tracking-[0.05em] text-[#40493d]">Source Type</TableHead>
                      <TableHead className="h-10 text-[11px] font-bold uppercase tracking-[0.05em] text-[#40493d]">Department</TableHead>
                      <TableHead className="h-10 text-[11px] font-bold uppercase tracking-[0.05em] text-[#40493d] text-right">Quantity</TableHead>
                      <TableHead className="h-10 text-[11px] font-bold uppercase tracking-[0.05em] text-[#40493d] text-right">CO2 Calculated</TableHead>
                      <TableHead className="h-10 text-[11px] font-bold uppercase tracking-[0.05em] text-[#40493d]">Generation</TableHead>
                      <TableHead className="h-10 text-[11px] font-bold uppercase tracking-[0.05em] text-[#40493d] text-center">Status</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {transactions.map((tx) => {
                      const sourceColorClass = getSourceColor(tx.sourceType)
                      
                      return (
                        <TableRow key={tx.id} className="h-[56px] border-b-[#E2E8F0] hover:bg-[#F7F8FA]/50">
                          <TableCell className="text-[13px] font-medium text-[#707A6C]">
                            {tx.createdAt.split('T')[0]}
                          </TableCell>
                          <TableCell>
                            <div className="flex items-center gap-2 text-[13px] font-bold text-[#191C1E]">
                              <div className={`rounded-md p-1 ${sourceColorClass}`}>
                                {getSourceIcon(tx.sourceType)}
                              </div>
                              {tx.sourceType}
                            </div>
                          </TableCell>
                          <TableCell className="text-[13px] font-bold text-[#191C1E]">
                            {tx.departmentName || "System"}
                          </TableCell>
                          <TableCell className="text-[13px] font-semibold text-[#707A6C] text-right">
                            {tx.quantity.toLocaleString(undefined, { maximumFractionDigits: 2 })}
                          </TableCell>
                          <TableCell className="text-[13px] font-bold text-[#0D631B] text-right">
                            {tx.co2Calculated.toLocaleString(undefined, { maximumFractionDigits: 2 })} kg
                          </TableCell>
                          <TableCell>
                            {tx.autoGenerated ? (
                              <span className="inline-flex items-center rounded-full bg-[#E1F0FF] px-2.5 py-0.5 text-[11px] font-bold tracking-[0.02em] text-[#005DB7]">
                                AUTO
                              </span>
                            ) : (
                              <span className="inline-flex items-center rounded-full bg-[#E2E8F0] px-2.5 py-0.5 text-[11px] font-bold tracking-[0.02em] text-[#40493d]">
                                MANUAL
                              </span>
                            )}
                          </TableCell>
                          <TableCell className="text-center">
                            {tx.anomalyFlag ? (
                              <span className="inline-flex items-center gap-1 text-[#BA1A1A]" title="Anomaly detected">
                                <AlertCircle className="h-4 w-4" />
                              </span>
                            ) : (
                              <span className="text-[#0D631B] font-bold text-[13px]">OK</span>
                            )}
                          </TableCell>
                        </TableRow>
                      )
                    })}
                  </TableBody>
                </Table>
              </div>
            )}

            {/* Pagination */}
            {!loading && !error && totalPages > 0 && (
              <div className="flex items-center justify-between border-t border-[#E2E8F0] pt-4">
                <span className="text-[12px] font-semibold text-[#707A6C]">
                  Page {page} of {totalPages}
                </span>
                <div className="flex items-center gap-2">
                  <Button
                    disabled={page <= 1}
                    variant="outline"
                    onClick={() => setPage(page - 1)}
                    className="h-[32px] px-3 border-[#E2E8F0] text-[#707A6C] rounded-[6px] text-[12px] font-semibold"
                  >
                    Prev
                  </Button>
                  <span className="h-8 w-8 rounded-[6px] bg-[#0D631B] text-white flex items-center justify-center text-[12px] font-bold">
                    {page}
                  </span>
                  <Button
                    disabled={page >= totalPages}
                    variant="outline"
                    onClick={() => setPage(page + 1)}
                    className="h-[32px] px-3 border-[#E2E8F0] text-[#40493d] rounded-[6px] text-[12px] font-semibold hover:bg-[#F7F8FA]"
                  >
                    Next
                  </Button>
                </div>
              </div>
            )}
          </div>

        </div>
      </main>
    </div>
  )
}
