from datetime import datetime
from typing import Generic, TypeVar, Optional, List
from pydantic import BaseModel, Field
from prisma.enums import GoalStatus, SourceType

T = TypeVar("T")

class PaginatedResponse(BaseModel, Generic[T]):
    items: List[T]
    total: int
    page: int
    page_size: int

# ── Emission Factors ──────────────────────────────────────────────────────────

class EmissionFactorCreate(BaseModel):
    activityType: str = Field(..., examples=["Electricity Grid Grid-mix"])
    unit: str = Field(..., examples=["kWh"])
    co2PerUnit: float = Field(..., description="CO2 emissions in kg per unit", examples=[0.475])
    source: str = Field(..., examples=["DEFRA 2023"])
    effectiveDate: datetime

class EmissionFactorUpdate(BaseModel):
    activityType: Optional[str] = None
    unit: Optional[str] = None
    co2PerUnit: Optional[float] = None
    source: Optional[str] = None
    effectiveDate: Optional[datetime] = None

class EmissionFactorResponse(BaseModel):
    id: str
    activityType: str
    unit: str
    co2PerUnit: float
    source: str
    effectiveDate: datetime
    createdAt: datetime
    updatedAt: datetime

# ── Product ESG Profiles ──────────────────────────────────────────────────────

class ProductEsgProfileCreate(BaseModel):
    productName: str = Field(..., examples=["Eco Friendly Chair"])
    sku: str = Field(..., examples=["FUR-CH-01"])
    carbonFootprint: float = Field(..., description="Carbon footprint per unit in kg CO2", examples=[24.5])
    recyclablePct: float = Field(..., description="Percentage of recyclable material (0-100)", examples=[85.0])
    notes: Optional[str] = None

class ProductEsgProfileUpdate(BaseModel):
    productName: Optional[str] = None
    sku: Optional[str] = None
    carbonFootprint: Optional[float] = None
    recyclablePct: Optional[float] = None
    notes: Optional[str] = None

class ProductEsgProfileResponse(BaseModel):
    id: str
    productName: str
    sku: str
    carbonFootprint: float
    recyclablePct: float
    notes: Optional[str] = None
    createdAt: datetime
    updatedAt: datetime

# ── Carbon Transactions ──────────────────────────────────────────────────────

class CarbonTransactionCreate(BaseModel):
    departmentId: str
    sourceType: SourceType
    sourceRecordId: Optional[str] = None
    emissionFactorId: Optional[str] = None
    productEsgProfileId: Optional[str] = None
    quantity: float
    co2Calculated: Optional[float] = None

class CarbonTransactionUpdate(BaseModel):
    departmentId: Optional[str] = None
    sourceType: Optional[SourceType] = None
    sourceRecordId: Optional[str] = None
    emissionFactorId: Optional[str] = None
    productEsgProfileId: Optional[str] = None
    quantity: Optional[float] = None
    co2Calculated: Optional[float] = None
    anomalyFlag: Optional[bool] = None

class CarbonTransactionResponse(BaseModel):
    id: str
    departmentId: str
    departmentName: Optional[str] = None
    sourceType: SourceType
    sourceRecordId: Optional[str] = None
    emissionFactorId: Optional[str] = None
    emissionFactorName: Optional[str] = None
    productEsgProfileId: Optional[str] = None
    productName: Optional[str] = None
    quantity: float
    co2Calculated: float
    autoGenerated: bool
    anomalyFlag: bool
    createdById: Optional[str] = None
    createdAt: datetime

# ── Environmental Goals ──────────────────────────────────────────────────────

class EnvironmentalGoalCreate(BaseModel):
    departmentId: str
    name: str = Field(..., examples=["Reduce Fleet Emissions"])
    targetCo2: float = Field(..., description="Target CO2 emissions in kg", examples=[500000.0])
    deadline: datetime

class EnvironmentalGoalUpdate(BaseModel):
    departmentId: Optional[str] = None
    name: Optional[str] = None
    targetCo2: Optional[float] = None
    deadline: Optional[datetime] = None
    status: Optional[GoalStatus] = None

class EnvironmentalGoalResponse(BaseModel):
    id: str
    departmentId: str
    departmentName: Optional[str] = None
    name: str
    targetCo2: float
    currentCo2: float
    progressPct: float
    deadline: datetime
    status: GoalStatus
    createdAt: datetime
    updatedAt: datetime

# ── Environmental Score ──────────────────────────────────────────────────────

class EnvironmentalScoreResponse(BaseModel):
    departmentId: Optional[str] = None
    score: float
    goalCount: int
    periodStart: datetime
    periodEnd: datetime
