// Auth & Users
export type User = {
  id: string
  name: string
  email: string
  role: 'super_admin' | 'dept_head' | 'employee' | 'auditor'
  department_id: string | null
  xp: number
  points: number
}
export type LoginRequest = { email: string; password: string }
export type LoginResponse = { access_token: string; token_type: 'bearer' }
export type AuthError = { code: string; message: string; details?: any }

// Environmental — aligned with backend camelCase response schemas

export type EmissionFactor = {
  id: string
  activityType: string
  unit: string
  co2PerUnit: number
  source: string
  effectiveDate: string
  createdAt: string
  updatedAt: string
}

export type ProductEsgProfile = {
  id: string
  productName: string
  sku: string
  carbonFootprint: number
  recyclablePct: number
  notes: string | null
  createdAt: string
  updatedAt: string
}

export type CarbonTransaction = {
  id: string
  departmentId: string
  departmentName: string | null
  sourceType: 'PURCHASE' | 'MANUFACTURING' | 'EXPENSE' | 'FLEET'
  sourceRecordId: string | null
  emissionFactorId: string | null
  emissionFactorName: string | null
  productEsgProfileId: string | null
  productName: string | null
  quantity: number
  co2Calculated: number
  autoGenerated: boolean
  anomalyFlag: boolean
  createdById: string | null
  createdAt: string
}

export type EnvironmentalGoal = {
  id: string
  departmentId: string
  departmentName: string | null
  name: string
  targetCo2: number
  currentCo2: number
  progressPct: number
  deadline: string
  status: 'ACTIVE' | 'ON_TRACK' | 'AT_RISK' | 'COMPLETED'
  createdAt: string
  updatedAt: string
}

// Social
export type CsrActivity = {
  id: string; title: string; category_id: string; description: string;
  department_id: string; evidence_required: boolean;
  status: string; created_at: string
}
export type EmployeeParticipation = {
  id: string; employee_id: string; csr_activity_id: string;
  proof_url: string | null;
  approval_status: 'pending' | 'approved' | 'rejected';
  points_earned: number; completion_date: string | null
}

// Governance
export type Policy = {
  id: string; title: string; body: string; category: string;
  version: string; effective_date: string; status: string
}
export type PolicyAcknowledgement = {
  id: string; employee_id: string; policy_id: string; acknowledged_at: string
}
export type Audit = {
  id: string; title: string; department_id: string; auditor_id: string;
  audit_date: string; findings_summary: string | null;
  status: 'scheduled' | 'under_review' | 'completed'
}
export type ComplianceIssue = {
  id: string; audit_id: string;
  severity: 'low' | 'medium' | 'high';
  description: string; owner_id: string;
  due_date: string; status: 'open' | 'resolved'; overdue: boolean
}

// Gamification
export type Challenge = {
  id: string; title: string; category_id: string; description: string;
  xp: number; difficulty: 'easy' | 'medium' | 'hard';
  evidence_required: boolean; deadline: string;
  status: 'draft' | 'active' | 'under_review' | 'completed' | 'archived'
}
export type ChallengeParticipation = {
  id: string; challenge_id: string; employee_id: string;
  progress_pct: number; proof_url: string | null;
  approval_status: 'pending' | 'approved' | 'rejected';
  xp_awarded: number
}
export type Badge = {
  id: string; name: string; description: string;
  icon_url: string; unlock_rule: Record<string, any>
}
export type UserBadge = {
  badge: Badge; unlocked: boolean; unlocked_at: string | null
}
export type Reward = {
  id: string; name: string; description: string;
  points_required: number; stock: number; status: string
}
export type LeaderboardEntry = {
  rank: number; user_id: string; name: string;
  department: string; xp: number
}

// Dashboard & Scoring
export type DepartmentScore = {
  id: string; department_id: string;
  environmental_score: number; social_score: number;
  governance_score: number; total_score: number;
  period_start: string; period_end: string
}
export type DashboardSummary = {
  overall_esg_score: number;
  environmental_score: number; social_score: number; governance_score: number;
  trend: Array<{ period: string; score: number }>
  dept_rankings: Array<{ department_id: string; department_name: string; total_score: number }>
}
export type RecentActivityItem = {
  id: string; type: string; payload: Record<string, any>;
  read: boolean; created_at: string
}

// Reports
export type CustomReportRequest = {
  date_range: { start: string; end: string }
  department_ids: string[]
  module: string
  employee_id?: string
  challenge_id?: string
  esg_category?: string
}
export type ReportExportRequest = {
  format: 'pdf' | 'excel' | 'csv'
  report_id?: string
  filters: CustomReportRequest
}
export type NlQueryRequest = { prompt: string }
export type NlQueryResponse = {
  data: any[]
  resolved_filters: CustomReportRequest
  columns: Array<{ key: string; label: string }>
}

// Settings
export type Department = {
  id: string; name: string; code: string;
  head_user_id: string | null; parent_department_id: string | null;
  employee_count: number; status: string; created_at: string
}
export type Category = {
  id: string; name: string;
  type: 'csr_activity' | 'challenge'; status: string
}
export type EsgConfig = {
  environmental_weight: number; social_weight: number; governance_weight: number;
  auto_emission_calc: boolean; evidence_required: boolean;
  badge_auto_award: boolean; notification_channels: string[]
}
export type Notification = {
  id: string; user_id: string; type: string;
  payload: Record<string, any>; read: boolean; created_at: string
}

// Pagination — matches backend PaginatedResponse
export type PaginatedResponse<T> = {
  items: T[]
  total: number
  page: number
  page_size: number
}

// Shared Error
export type ApiError = {
  code: string
  message: string
  details?: any
}
